# Production values for atom chart
# This file contains production-ready values for the AtoM application

################################################################################
#                          Configurações Gerais                                #
################################################################################
general:
  # UID do usuário para execução dos contêineres
  # Escolha este valor com base no intervalo permitido do seu projeto OpenShift
  # (verifique a anotação openshift.io/sa.scc.uid-range)
  user_uid: "1002150000"

  # Namespace para instalação (será substituído pelo namespace de lançamento)
  namespace: npr-prodest-pds


################################################################################
#                   Configurações de segurança para OpenShift                  #
################################################################################
security:
  # ServiceAccount para os pods
  serviceAccount:
    # create: true
    name: "atom"
  serviceAccountAnyUID:
    # create: true
    name: "anyuid-atom"
  # # SecurityContextConstraints para OpenShift
  # scc:
  #   # Usar SCC existente ou criar uma personalizada
  #   # Valores possíveis: "restricted", "nonroot", "anyuid", "custom"
  #   use: "anyuid"

  #   # Nome da SCC personalizada (se use: "custom")
  #   custom_name: "archivematica-scc"

################################################################################
#                  Configurações de rota para OpenShift                        #
################################################################################
route:
  enabled: true
  tls: true
  hostname: "atom.k8s-npr.es.gov.br"

# global:
#   domain: "k8s-npr.es.gov.br"
#   imageRegistry: "registry.redhat.io"
#   storageClass: "ocs-storagecluster-ceph-rbd"
#   imagePullSecrets:
#     - name: registry-secret

################################################################################
#                   Configurações AtoM application                             #
################################################################################
atom:
  enabled: true
  replicas: 1
  image:
    repository: "registry.prodest.es.gov.br/sgint/atom"
    pullPolicy: Always
    tag: "latest"
  env:
    # - name: ATOM_DEVELOPMENT_MODE
    #   value: on"
    # - name: NODE_ENV
    #   value: development
    - name: ATOM_ELASTICSEARCH_HOST
      value: "10.242.94.10"
    # - name: ATOM_MEMCACHED_HOST
    #   value: memcached
    # - name: ATOM_GEARMAND_HOST
    #   value: gearmand
    # - name: ATOM_MYSQL_DSN
    #   value: mysql:host=percona;port=3306;dbname=atom;charset=utf8mb4
    # - name: ATOM_MYSQL_USERNAME
    #   value: atom
    # - name: ATOM_MYSQL_PASSWORD
    #   value: atom_12345
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 500Mi

################################################################################
#                   Configurações AtoM worker                                  #
################################################################################
atomWorker:
  enabled: true
  replicas: 1
  image:
    repository: "registry.prodest.es.gov.br/sgint/atom"
    pullPolicy: Always
    tag: "latest"
  env:
    # - name: ATOM_DEVELOPMENT_MODE
    #   value: on"
    # - name: NODE_ENV
    #   value: development
    - name: ATOM_ELASTICSEARCH_HOST
      value: "10.242.94.10"
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 500Mi

################################################################################
#                   Configurações Nginx                                        #
################################################################################

nginx:
  enabled: true
  replicas: 1
  image:
    repository: "registry.prodest.es.gov.br/docker/nginxinc/nginx-unprivileged"
    pullPolicy: Always
    tag: "latest"

  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi


################################################################################
#                   Configurações MySQL                                        #
################################################################################

mysql:
  enabled: true
  replicas: 1

  image:
    repository: percona #TODO: VERIFICAR PARA UTILIZAR O PERCONA:8.0
    tag: "8"
    pullPolicy: IfNotPresent
  # auth:
  #   rootPassword: "secure-root-password-change-me"
  #   password: "secure-atom-password-change-me"

  # Configurações do banco de dados
  db:
    #name: "archivematica_db"
    user: "atom"
    password: "atom_12345"
    rootPassword: "root_password"

  resources:
    limits:
      cpu: 2000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 500Mi

  persistence:
    enabled: true
    size: 1Gi
    accessMode: ReadWriteOnce

#                   Configurações elasticsearch                                    #
################################################################################

elasticsearch:
  enabled: false

################################################################################
#                   Configurações Memcached                                    #
################################################################################

memcached:
  enabled: true
  replicas: 1
  image:
    repository: memcached
    tag: "latest"
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi


################################################################################
#                   Configurações Gearman                                      #
################################################################################

gearmand:
  enabled: true
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi
  image:
    repository: artefactual/gearmand
    tag: "1.1.18-alpine"
    pullPolicy: IfNotPresent

# # Security context for production
# securityContext:
#   enabled: true
#   runAsNonRoot: true
#   runAsUser: 1001
#   fsGroup: 1001

# # Pod security context
# podSecurityContext:
#   enabled: true
#   runAsNonRoot: true
#   runAsUser: 1001
#   fsGroup: 1001

# # Resource quotas and limits
# nodeSelector:
#   node-role.kubernetes.io/worker: ""

# # Tolerations for specific nodes
# tolerations:
#   - key: "dedicated"
#     operator: "Equal"
#     value: "atom"
#     effect: "NoSchedule"

# # Affinity rules for high availability
# affinity:
#   podAntiAffinity:
#     preferredDuringSchedulingIgnoredDuringExecution:
#       - weight: 100
#         podAffinityTerm:
#           labelSelector:
#             matchExpressions:
#               - key: app.kubernetes.io/name
#                 operator: In
#                 values:
#                   - atom
#           topologyKey: kubernetes.io/hostname

# # OpenShift specific configurations
# openshift:
#   enabled: true
#   scc:
#     enabled: true
#     name: "restricted"


################################################################################
#                     Configurações volumes compartilhados                     #
################################################################################
volumes:
  # Volume para dados do pipeline
  uploads:
    enabled: true
    size: 1Gi
    #storageClass: ""
    accessMode: ReadWriteMany
    #resourcePolicy: keep

  # Volume para dados de staging
  cache:
    enabled: true
    size: 1Gi
    #storageClass: ""
    accessMode: ReadWriteMany
    #resourcePolicy: keep

  # Volume para dados de localização
  composer:
    enabled: true
    size: 1Gi
    #storageClass: ""
    accessMode: ReadWriteMany
    #resourcePolicy: keep

  # Volume para compartilhamento de transferência
  npm:
    enabled: true
    size: 1Gi
    #storageClass: ""
    accessMode: ReadWriteMany
    #resourcePolicy: keep