apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "atom.worker.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "atom.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.atomWorker.replicaCount }}
  selector:
    matchLabels:
      {{- include "atom.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "atom.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "atom.serviceAccountName" . }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext:
        {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: atom-worker
          image: {{ include "atom.image" . }}
          imagePullPolicy: {{ .Values.atomWorker.image.pullPolicy }}
          command: ["docker/entrypoint.sh"]
          args: ["worker"]
          envFrom:
            - configMapRef:
                name: {{ include "atom.fullname" . }}-config
            - secretRef:
                name: {{ include "atom.mysql.fullname" . }}-secret
          resources:
            {{- toYaml .Values.atomWorker.resources | nindent 12 }}
          volumeMounts:
            - name: uploads
              mountPath: /atom/src/uploads
            - name: cache
              mountPath: /atom/src/cache
          {{- if .Values.securityContext.enabled }}
          securityContext:
            {{- omit .Values.securityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: {{ include "atom.fullname" . }}-uploads-pvc
        - name: cache
          persistentVolumeClaim:
            claimName: {{ include "atom.fullname" . }}-cache-pvc
      restartPolicy: {{ .Values.atomWorker.restartPolicy }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
