apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "atom.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "atom.labels" . | nindent 4 }}
    app.kubernetes.io/component: atom
spec:
  replicas: {{ .Values.atom.replicaCount }}
  selector:
    matchLabels:
      {{- include "atom.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: atom
  template:
    metadata:
      labels:
        {{- include "atom.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: atom
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "atom.serviceAccountName" . }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext:
        {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: atom
          image: {{ include "atom.image" . }}
          imagePullPolicy: {{ .Values.atom.image.pullPolicy }}
          command: ["docker/entrypoint.sh"]
          args: ["fpm"]
          ports:
            - name: php-fpm
              containerPort: 9000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "atom.fullname" . }}-config
            - secretRef:
                name: {{ include "atom.mysql.fullname" . }}-secret
          {{- if .Values.atom.livenessProbe.enabled }}
          livenessProbe:
            tcpSocket:
              port: php-fpm
            initialDelaySeconds: {{ .Values.atom.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.atom.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.atom.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.atom.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.atom.livenessProbe.successThreshold }}
          {{- end }}
          {{- if .Values.atom.readinessProbe.enabled }}
          readinessProbe:
            tcpSocket:
              port: php-fpm
            initialDelaySeconds: {{ .Values.atom.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.atom.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.atom.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.atom.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.atom.readinessProbe.successThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.atom.resources | nindent 12 }}
          volumeMounts:
            - name: uploads
              mountPath: /atom/src/uploads
            - name: cache
              mountPath: /atom/src/cache
          {{- if .Values.securityContext.enabled }}
          securityContext:
            {{- omit .Values.securityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: {{ include "atom.fullname" . }}-uploads-pvc
        - name: cache
          persistentVolumeClaim:
            claimName: {{ include "atom.fullname" . }}-cache-pvc
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
