{{- if .Values.atomWorker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "atom.fullname" . }}-worker
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "atom.component.labels" (list . "worker") | nindent 4 }}
spec:
  replicas: {{ .Values.atomWorker.replicas }}
  selector:
    matchLabels:
      {{- include "atom.component.selectorLabels" (list . "worker") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "atom.component.selectorLabels" (list . "worker") | nindent 8 }}
    spec:
      serviceAccountName: {{ include "atom.serviceAccountName" . }}
      containers:
        - name: atom-worker
          image: "{{ .Values.atomWorker.image.repository }}:{{ .Values.atomWorker.image.tag }}"
          imagePullPolicy: {{ .Values.atomWorker.image.pullPolicy }}
          command: ["docker/entrypoint.sh"]
          args: ["worker"]
          env:
            {{- if .Values.memcached.enabled }}
            - name: ATOM_MEMCACHED_HOST
              value: {{ include "atom.fullname" . }}-memcached
            {{- end }}
            {{- if .Values.gearmand.enabled }}
            - name: ATOM_GEARMAND_HOST
              value: {{ include "atom.fullname" . }}-gearmand
            {{- end }}
            {{- if .Values.mysql.enabled }}
            - name: ATOM_MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "atom.fullname" . }}-mysql-secrets
                  key: ATOM_MYSQL_USERNAME
            - name: ATOM_MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "atom.fullname" . }}-mysql-secrets
                  key: ATOM_MYSQL_PASSWORD
            - name: ATOM_MYSQL_DSN
              secretKeyRef:
                  name: {{ include "atom.fullname" . }}-mysql-secrets
                  key: ATOM_MYSQL_DSN
            {{- end }}
            {{- if .Values.elasticsearch.enabled }}
            - name: ATOM_ELASTICSEARCH_HOST
              value: {{ include "atom.fullname" . }}-elasticsearch
            {{- end }}
            {{- toYaml .Values.atom.env | nindent 12 }}
          resources:
            {{- toYaml .Values.atomWorker.resources | nindent 12 }}
          volumeMounts:
            - name: uploads
              mountPath: /atom/src/uploads
            - name: cache
              mountPath: /atom/src/cache
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: {{ include "atom.fullname" . }}-uploads-pvc
        - name: cache
          persistentVolumeClaim:
            claimName: {{ include "atom.fullname" . }}-cache-pvc
        - name: composer-deps
          persistentVolumeClaim:
            claimName: {{ include "atom.fullname" . }}-composer-deps-pvc
      restartPolicy: {{ .Values.atomWorker.restartPolicy }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
