{{- if .Values.memcached.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "atom.fullname" . }}-memcached
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "atom.component.labels" (list . "memcached") | nindent 4 }}
spec:
  ports:
    - port: 11211
      targetPort: 11211
      protocol: TCP
      name: memcached
  selector:
{{- include "atom.component.selectorLabels" (list . "memcached") | nindent 4 }}
{{- end }}