{{- if .Values.nginx.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "atom.fullname" . }}-nginx
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "atom.component.labels" (list . "nginx") | nindent 4 }}
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: {{ .Values.nginx.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "atom.component.selectorLabels" (list . "nginx") | nindent 4 }}
{{- end }}