{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "atom.fullname" . }}-mysql
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "atom.component.labels" (list . "mysql") | nindent 4 }}
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: mysql
  selector:
    {{- include "atom.component.selectorLabels" (list . "mysql") | nindent 4 }}
{{- end }}