apiVersion: v1
kind: Secret
metadata:
  name: {{ include "atom.fullname" . }}-mysql-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "atom.labels" . | nindent 4 }}
type: Opaque
data:
  # Senhas do MySQL (codificadas em Base64)
  MYSQL_USER: {{ .Values.mysql.db.user | b64enc | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.db.rootPassword | b64enc | quote }}
  MYSQL_PASSWORD: {{ .Values.mysql.db.password | b64enc | quote }}
  ATOM_MYSQL_USERNAME: {{ .Values.mysql.db.password | b64enc | quote }}
  ATOM_MYSQL_PASSWORD: {{ .Values.mysql.db.password | b64enc | quote }}
  ATOM_MYSQL_DSN: {{ printf "mysql:host=%s-mysql;port=3306;dbname=atom;charset=utf8mb4" (include "atom.fullname" .) | b64enc | quote }}